using ExchangeRates.Domain.Enums;

namespace ExchangeRates.Domain.Constants;

/// <summary>
/// Defines a priority order for canonical currencies based on their global significance and usage
/// </summary>
public static class CanonicalCurrencyPriority_ {
	public static readonly ECurrencyISO[] CanonicalCurrencies = [
	// Tier 1 — Global major currencies
	ECurrencyISO.USD,
	ECurrencyISO.EUR,
	ECurrencyISO.GBP,
	ECurrencyISO.JPY,
	ECurrencyISO.CHF,

	// Tier 2 — Major international / developed-market currencies
	ECurrencyISO.CNY,
	ECurrencyISO.CAD,
	ECurrencyISO.AUD,
	ECurrencyISO.HKD,
	ECurrencyISO.SGD,
	ECurrencyISO.KRW,
	ECurrencyISO.INR,
	ECurrencyISO.NZD,
	ECurrencyISO.SEK,
	ECurrencyISO.NOK,
	ECurrencyISO.DKK,

	// Tier 3 — Major emerging / regional currencies
	ECurrencyISO.BRL,
	ECurrencyISO.MXN,
	ECurrencyISO.ZAR,
	ECurrencyISO.TWD,
	ECurrencyISO.PLN,
	ECurrencyISO.TRY,
	ECurrencyISO.SAR,
	ECurrencyISO.AED,
	ECurrencyISO.THB,
	ECurrencyISO.ILS,
	ECurrencyISO.MYR,
	ECurrencyISO.IDR,
	ECurrencyISO.CZK,
	ECurrencyISO.HUF,
	ECurrencyISO.PHP,

	// Tier 4 — Significant regional currencies
	ECurrencyISO.CLP,
	ECurrencyISO.COP,
	ECurrencyISO.PEN,
	ECurrencyISO.RON,
	ECurrencyISO.ISK,
	ECurrencyISO.KWD,
	ECurrencyISO.QAR,
	ECurrencyISO.BHD,
	ECurrencyISO.OMR,
	ECurrencyISO.VND,
	ECurrencyISO.PKR,
	ECurrencyISO.BDT,
	ECurrencyISO.EGP,
	ECurrencyISO.NGN,
	ECurrencyISO.KZT,
	ECurrencyISO.MAD,
	ECurrencyISO.KES,
	ECurrencyISO.UAH,
	ECurrencyISO.RSD,

	// Tier 5 — Other active national currencies
	ECurrencyISO.ARS,
	ECurrencyISO.UYU,
	ECurrencyISO.PYG,
	ECurrencyISO.BOB,
	ECurrencyISO.CRC,
	ECurrencyISO.DOP,
	ECurrencyISO.GTQ,
	ECurrencyISO.HNL,
	ECurrencyISO.NIO,
	ECurrencyISO.JMD,
	ECurrencyISO.TTD,
	ECurrencyISO.GYD,
	ECurrencyISO.SRD,
	ECurrencyISO.HTG,
	ECurrencyISO.CUP,
	ECurrencyISO.DZD,
	ECurrencyISO.TND,
	ECurrencyISO.LYD,
	ECurrencyISO.GHS,
	ECurrencyISO.ETB,
	ECurrencyISO.TZS,
	ECurrencyISO.UGX,
	ECurrencyISO.RWF,
	ECurrencyISO.ZMW,
	ECurrencyISO.BWP,
	ECurrencyISO.MUR,
	ECurrencyISO.MZN,
	ECurrencyISO.AOA,
	ECurrencyISO.NAD,
	ECurrencyISO.SZL,
	ECurrencyISO.LSL,
	ECurrencyISO.MGA,
	ECurrencyISO.MWK,
	ECurrencyISO.SCR,
	ECurrencyISO.CVE,
	ECurrencyISO.GMD,
	ECurrencyISO.GNF,
	ECurrencyISO.SLE,
	ECurrencyISO.LRD,
	ECurrencyISO.MRU,
	ECurrencyISO.SOS,
	ECurrencyISO.SDG,
	ECurrencyISO.SSP,
	ECurrencyISO.BIF,
	ECurrencyISO.CDF,

	// Middle East / Central & South Asia
	ECurrencyISO.JOD,
	ECurrencyISO.IQD,
	ECurrencyISO.IRR,
	ECurrencyISO.LBP,
	ECurrencyISO.YER,
	ECurrencyISO.AFN,
	ECurrencyISO.LKR,
	ECurrencyISO.NPR,
	ECurrencyISO.BTN,
	ECurrencyISO.MVR,
	ECurrencyISO.KGS,
	ECurrencyISO.TJS,
	ECurrencyISO.TMT,
	ECurrencyISO.UZS,
	ECurrencyISO.AZN,
	ECurrencyISO.AMD,
	ECurrencyISO.GEL,

	// Southeast / East Asia & Pacific
	ECurrencyISO.BND,
	ECurrencyISO.MOP,
	ECurrencyISO.MMK,
	ECurrencyISO.KHR,
	ECurrencyISO.LAK,
	ECurrencyISO.MNT,
	ECurrencyISO.KPW,
	ECurrencyISO.FJD,
	ECurrencyISO.PGK,
	ECurrencyISO.WST,
	ECurrencyISO.TOP,
	ECurrencyISO.VUV,
	ECurrencyISO.SBD,

	// Europe / smaller currencies
	ECurrencyISO.ALL,
	ECurrencyISO.MKD,
	ECurrencyISO.MDL,
	ECurrencyISO.BYN,
	ECurrencyISO.BAM,

	// Small / pegged / territorial currencies
	ECurrencyISO.BMD,
	ECurrencyISO.KYD,
	ECurrencyISO.BSD,
	ECurrencyISO.BBD,
	ECurrencyISO.BZD,
	ECurrencyISO.AWG,
	ECurrencyISO.PAB,
	ECurrencyISO.XCD,
	ECurrencyISO.DJF,
	ECurrencyISO.KMF,
	ECurrencyISO.XAF,
	ECurrencyISO.XOF,
	ECurrencyISO.XPF,
	ECurrencyISO.FKP,
	ECurrencyISO.GIP,
	ECurrencyISO.SHP,

	// Other current ISO monetary units / special-purpose codes
	ECurrencyISO.BOV,
	ECurrencyISO.CHE,
	ECurrencyISO.CHW,
	ECurrencyISO.CLF,
	ECurrencyISO.COU,
	ECurrencyISO.MXV,
	ECurrencyISO.USN,
	ECurrencyISO.UYI,
	ECurrencyISO.UYW,
	ECurrencyISO.XCG,
	ECurrencyISO.XSU,
	ECurrencyISO.XUA,

	// International monetary unit
	ECurrencyISO.XDR,

	// Metals
	ECurrencyISO.XAU,
	ECurrencyISO.XAG,
	ECurrencyISO.XPT,
	ECurrencyISO.XPD,

	// Historic currencies
	ECurrencyISO.ADP,
	ECurrencyISO.AFA,
	ECurrencyISO.ALK,
	ECurrencyISO.ANG,
	ECurrencyISO.AOK,
	ECurrencyISO.AON,
	ECurrencyISO.AOR,
	ECurrencyISO.ARA,
	ECurrencyISO.ARP,
	ECurrencyISO.ARY,
	ECurrencyISO.ATS,
	ECurrencyISO.AYM,
	ECurrencyISO.AZM,
	ECurrencyISO.BAD,
	ECurrencyISO.BEC,
	ECurrencyISO.BEF,
	ECurrencyISO.BEL,
	ECurrencyISO.BGJ,
	ECurrencyISO.BGK,
	ECurrencyISO.BGL,
	ECurrencyISO.BOP,
	ECurrencyISO.BRB,
	ECurrencyISO.BRC,
	ECurrencyISO.BRE,
	ECurrencyISO.BRN,
	ECurrencyISO.BRR,
	ECurrencyISO.BUK,
	ECurrencyISO.BYB,
	ECurrencyISO.BYR,
	ECurrencyISO.CHC,
	ECurrencyISO.CSD,
	ECurrencyISO.CSJ,
	ECurrencyISO.CSK,
	ECurrencyISO.CUC,
	ECurrencyISO.CYP,
	ECurrencyISO.DDM,
	ECurrencyISO.DEM,
	ECurrencyISO.ECS,
	ECurrencyISO.ECV,
	ECurrencyISO.EEK,
	ECurrencyISO.ESA,
	ECurrencyISO.ESB,
	ECurrencyISO.ESP,
	ECurrencyISO.FIM,
	ECurrencyISO.FRF,
	ECurrencyISO.GEK,
	ECurrencyISO.GHC,
	ECurrencyISO.GHP,
	ECurrencyISO.GNE,
	ECurrencyISO.GNS,
	ECurrencyISO.GQE,
	ECurrencyISO.GRD,
	ECurrencyISO.GWE,
	ECurrencyISO.GWP,
	ECurrencyISO.HRD,
	ECurrencyISO.HRK,
	ECurrencyISO.IEP,
	ECurrencyISO.ILP,
	ECurrencyISO.ILR,
	ECurrencyISO.ISJ,
	ECurrencyISO.ITL,
	ECurrencyISO.LAJ,
	ECurrencyISO.LSM,
	ECurrencyISO.LTL,
	ECurrencyISO.LTT,
	ECurrencyISO.LUC,
	ECurrencyISO.LUF,
	ECurrencyISO.LUL,
	ECurrencyISO.LVL,
	ECurrencyISO.LVR,
	ECurrencyISO.MGF,
	ECurrencyISO.MLF,
	ECurrencyISO.MRO,
	ECurrencyISO.MTL,
	ECurrencyISO.MTP,
	ECurrencyISO.MVQ,
	ECurrencyISO.MXP,
	ECurrencyISO.MZE,
	ECurrencyISO.MZM,
	ECurrencyISO.NIC,
	ECurrencyISO.NLG,
	ECurrencyISO.PEH,
	ECurrencyISO.PEI,
	ECurrencyISO.PES,
	ECurrencyISO.PLZ,
	ECurrencyISO.PTE,
	ECurrencyISO.RHD,
	ECurrencyISO.ROK,
	ECurrencyISO.ROL,
	ECurrencyISO.RUR,
	ECurrencyISO.SDD,
	ECurrencyISO.SDP,
	ECurrencyISO.SIT,
	ECurrencyISO.SKK,
	ECurrencyISO.SLL,
	ECurrencyISO.SRG,
	ECurrencyISO.STD,
	ECurrencyISO.SUR,
	ECurrencyISO.TJR,
	ECurrencyISO.TMM,
	ECurrencyISO.TPE,
	ECurrencyISO.TRL,
	ECurrencyISO.UAK,
	ECurrencyISO.UGS,
	ECurrencyISO.UGW,
	ECurrencyISO.USS,
	ECurrencyISO.UYN,
	ECurrencyISO.UYP,
	ECurrencyISO.VEB,
	ECurrencyISO.VEF,
	ECurrencyISO.VNC,
	ECurrencyISO.XEU,
	ECurrencyISO.YDD,
	ECurrencyISO.YUD,
	ECurrencyISO.YUM,
	ECurrencyISO.YUN,
	ECurrencyISO.ZAL,
	ECurrencyISO.ZMK,
	ECurrencyISO.ZRN,
	ECurrencyISO.ZRZ,
	ECurrencyISO.ZWC,
	ECurrencyISO.ZWD,
	ECurrencyISO.ZWL,
	ECurrencyISO.ZWN,
	ECurrencyISO.ZWR
];

	/// <summary>
	/// Gets the canonical currency pair, ensuring the base currency has a higher priority than the quote currency.
	/// </summary>
	/// <param name="currency1">The first currency.</param>
	/// <param name="currency2">The second currency.</param>
	/// <returns>A tuple containing the base and quote currencies in canonical order.</returns>
	public static (string Base, string Quote) GetCanonicalPair(string currency1, string currency2) {
		var priority1 = GetPriority(currency1);
		var priority2 = GetPriority(currency2);

		if (priority1 != priority2) {
			return priority1 < priority2 ? (currency1, currency2) : (currency2, currency1);
		}

		return string.CompareOrdinal(currency1.ToString(), currency2.ToString()) <= 0
			? (currency1, currency2)
			: (currency2, currency1);
	}

	private static readonly IReadOnlyDictionary<ECurrencyISO, int> CanonicalPriority = CanonicalCurrencies.Select((currency, index) => (currency, index))
																																										.ToDictionary(x => x.currency, x => x.index);

	public static int GetPriority(string currency) => CanonicalPriority.TryGetValue(currency, out var priority) ? priority : int.MaxValue;
}
