services:
  client:
    build:
      context: ./Clients/ExchangeRates.Client/exchangerates.client.react
      dockerfile: Dockerfile.Client
    container_name: exchangerates-client
    ports:
      - "8082:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile.Server
    container_name: exchangerates-server
    volumes:
    - ./Server/ExchangeRates.Server/logs:/app/logs
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: UAT
      ASPNETCORE_URLS: http://+:8080
    restart: unless-stopped

