FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY Server/ ./Server/

RUN dotnet restore Server/ExchangeRates.Server/ExchangeRates.Server.csproj

RUN dotnet publish Server/ExchangeRates.Server/ExchangeRates.Server.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "ExchangeRates.Server.dll"]