name: exchangerates

services:
  client:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.Client
    container_name: exchangerates-client
    ports:
      - "8082:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.Server
    container_name: exchangerates-server
    volumes:
    - ../Server/ExchangeRates.Server/logs:/app/logs
    ports:
      - "8090:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: UAT
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__ExchangeRates: ${EXCHANGERATES_CONNECTION_STRING}
    restart: unless-stopped

