FROM node:22-alpine AS build
WORKDIR /app

COPY Clients/ExchangeRates.Client/exchangerates.client.react/package*.json ./
RUN npm ci

COPY Clients/ExchangeRates.Client/exchangerates.client.react/ ./
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html/exchangerates/
COPY Clients/ExchangeRates.Client/exchangerates.client.react/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]