SELECT TOP (1000) [Id]
      ,[BankCode]
      ,[BankName]
      ,[CurrencyId]
      ,[IsActive]
      ,[CreatedAtUtc]
      ,[Priority]
      ,[CountryOfOrigin]
      ,[ApiUrl]
  FROM [ExchangeRates].[dbo].[CentralBank]
where apiurl is null

UPDATE dbo.CentralBank
SET ApiUrl = CASE BankCode

    /* Real APIs / machine-readable feeds */

    WHEN 'BCRP' THEN
        'https://estadisticas.bcrp.gob.pe/estadisticas/series/api'

    WHEN 'RBNZ' THEN
        'https://rbnz.govt.nz/-/media/project/sites/rbnz/files/statistics/series/b/b1/hb1-daily.xlsx'

    WHEN 'BCH' THEN
        'https://bchapi-am.developer.azure-api.net/api/v1'

    WHEN 'CBAZ' THEN
        'https://cbar.az/currencies/{date:dd.MM.yyyy}.xml'
        else apiurl
        end
       https://www.cbk.gov.kw/en/redirects/download?dfile=19JM6X5QPow273NHGR51sXjdwZ1yCDTCFZ8wgeV71TsetHmD6vyv458vLBSt31VuW8vPnEgk9yFID/9sZXIuLWrRfRhRiEStohAS4~1FpUlB2zUI7R0CLHK2Kp34SGI=&esIndex=autogenerated